'''The conversion of one data type into the other 
   data type is known as type casting 
   in python or type conversion in python'''
#int()
#float()
#str()
# x=int(1)
# y=int(546.78)
# z=int("772")
# print(type(x))
# print(type(y))
# print(type(z))
# print(x)
# print(y)
# print(z)
# x=float(1)
# y=float(546.78)
# z=float("772")
# w=float("17.56")
# print(type(x))
# print(type(y))
# print(type(z))
# print(type(w))
# print(x)
# print(y)
# print(z)
# print(w)
x=str("ha")
y=str(546.78)
z=str(772)
print(type(x))
print(type(y))
print(type(z))
print(x)
print(y)
print(z)
